### ISSUE TITLE
Payment Status

### ISSUE THREAD

**Issue by Bastiengrsd** [alcalyn/payplug-bundle#15]
Hi, 

How can i check the payment status in the PaymentListener ?

Moreover, where do I put the code after IPN request if my Listener are in another Bundle. The PayplugController already redirect in the Listner ?

Thanks for help and for this bundle !

**Comment by alcalyn** [comment]
Hello,

Does `IPN::getState()` do the trick ? (https://github.com/alcalyn/payplug-bundle/blob/master/Model/IPN.php#L75)

Wherever your listener class is, the IPN event is emitted to the Symfony EventDispatcher, so you can listen to it from everywhere, as long as you say that your class listens to the `event.payplug.ipn` event. See http://symfony.com/doc/current/event_dispatcher.html

Good luck !

**Comment by Bastiengrsd** [comment]
Oh thanks, I haven't see this method !
